language: python
sudo: false
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install . --progress-bar off
# command to run tests
script:
  - pytest
